#!/bin/bash
export TWITTER_CONSUMER_KEY=CONSUMERKEY
export TWITTER_CONSUMER_SECRET=CONSUMERSECRET
export TWITTER_USER_TOKEN=USERTOKEN
export TWITTER_USER_SECRET=USERSECRET
export TCAT_URL=/dmi-tcat/
export DB_PW=admin
export ADMIN_PW=admin
export TCAT_PW=tcat
docker-compose up -d
