CREATE DATABASE IF NOT EXISTS twittercapture DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'dmi' IDENTIFIED BY 'tcat';
GRANT ALL PRIVILEGES ON *.* TO 'dmi';
FLUSH PRIVILEGES;